### ISSUE TITLE
Installation Requirements showing dependency to js-controller (>=35.0.0) instead of "5.0.0"

### ISSUE THREAD

**Issue by FBruhns** [iobroker-community-adapters/ioBroker.comfoair#308]
It seems as if the installer dependencies check for 1.2.0 has a typo and instead of checking for (>= 5.0.0) is checking for js-controller (>= 35.0.0).

**Comment by mcm1957** [comment]
Thanks for reporting and sorry. Will fix it today.

**Comment by mcm1957** [comment]
fixed with 1.2.1
