### ISSUE TITLE
Problem connecting over ser2net/socat

### ISSUE THREAD

**Issue by SchwarzJJ** [iobroker-community-adapters/ioBroker.comfoair#33]
I have a rs232 cable connected to a usb serial adapter and use it with the openhab binding on the raspi pi connected to the usb2serial adapter. evyerything works fine with this config
Because I have a home server running ubuntu with docker containers I want to run iobroker in a container and connect to my usb2serial over ser2net. 
I am not able to get a connection over the ip of ser2net and also with entering the /dev/ttyNET0 port of socat in the configuration of my iobroker.
Do you have any idea what I can do? Do you suggest to buy a rs323ttl adapter?

**Comment by SchwarzJJ** [comment]
maybe the problem is my iobroker comfoair configuration where I only see "Comfair IP" and "Port". How can I enter the /dev/ttyNET0 for my serial port?

**Comment by forelleblau** [comment]
Sorry for the delayed answer. If you install the latest version of the adapter from github you can choose 'Serielle Verbinung' in the adapter-config. The you get a '/def...' instead of an 'IP....'
