### ISSUE TITLE
Boost

### ISSUE THREAD

**Issue by mfgdirk** [iobroker-community-adapters/ioBroker.comfoair#35]
Hallo,  Der Adapter ist super!! Das ist wahrscheinlich kein Issue sondern eher Zusatzfunktionen.

Ich vermisse den Wert Boost Funktion (WC-Lüftung) und 
Bootsdauer Kommando: 0x00 0xC9 (Zeit) Verzögerung abrufen Antwort: 0x00 0xCA Byte[4] Stosslüftung (Min)

Sowie sie eine einschaltbare Automatikfunktion : 0x00 0x99 Stufe setzen Daten: Byte[1] 0x00 = Auto

Bypasssteuerung per Schalter wäre auch noch cool!
Kommando: 0x00 0x09 Klappen setzen Daten: Byte[1] Byte[2] Bypass (1 = offen / 0 = geschlossen / 3 = Stop)

Aber nochmal der Adapter ist bereits super!

**Comment by ivo443** [comment]
> Hallo, Der Adapter ist super!! Das ist wahrscheinlich kein Issue sondern eher Zusatzfunktionen.
> 
> Ich vermisse den Wert Boost Funktion (WC-Lüftung) und
> Bootsdauer Kommando: 0x00 0xC9 (Zeit) Verzögerung abrufen Antwort: 0x00 0xCA Byte[4] Stosslüftung (Min)
> 
> Sowie sie eine einschaltbare Automatikfunktion : 0x00 0x99 Stufe setzen Daten: Byte[1] 0x00 = Auto
> 
> Bypasssteuerung per Schalter wäre auch noch cool!
> Kommando: 0x00 0x09 Klappen setzen Daten: Byte[1] Byte[2] Bypass (1 = offen / 0 = geschlossen / 3 = Stop)
> 
> Aber nochmal der Adapter ist bereits super!

Yep, das wäre cool!

**Comment by forelleblau** [comment]
ok, mach mich dahinter. Beim Bypass will ich aber nichts versprechen. Das geht meines Wissens nur wenn der Testmodus vorher eingeschaltet wird. Oder habt ihr da Erfahrung. Ihr seid natürlich auch gerne eingeladen das selber zu schreiben und den Adapter über einen entsprechenden Pull-Request zu bereichern. 
Die Auto-Stufe ist schon geschrieben und Issues sind durchaus dafür da, sich Zusatzfunktionen zu wünschen. Die sind mir sogar lieber als bug-reports....

**Comment by forelleblau** [comment]
Also, ab nochmal etwas rumgeschaut Ich finde / kriege nur das folgende hin:

Stosslüften: Da könnte ich Objekte für das Abrufen und Setzen der Verzögerungszeit in den Adapter aufnehmen. Wie der Stosslüftungsmodus ausgelöst wird, habe ich aber keine Angaben. Weiss da jemand mehr von euch?

Bypass: Ist wohl so wie oben geschrieben: Die Bypassklappe kann nur im Testmodus oder über die Komforttemperatur gesteuert werden. D.h. im Normalen Betrieb kann die Bypassklappe nicht direkt angesteuert werden.  In meiner Lüftungssteuerung über ein Script setze ich einach je nach Bedarf eine sehr hohe oder sehr tiefe Komforttemperatur, wenn ich den Bypass übersteuern will.

**Comment by ivo443** [comment]
Wie das integriert werden muss kann ich nicht sagen.
http://www.see-solutions.de/sonstiges/Protokollbeschreibung_ComfoAir.pdf
Ich habe die HEX Werte auch nicht gefunden. Evtl. geht das über "0x00 0x40 RF Kommando senden". Ich habe eine Zehnder RF Fernbedienung (https://www.lueftungsmarkt.de/zehnder-bedieneinheit-rf-funkfernbedienung) da dran mit welcher ich via Button "Zeitsymbol" und dem Betätigen: Kurz Stufe 3, vorübergehend 10 Minuten / Lang  (> 2 Sek.) Stufe 3, vorübergehend 30 Minuten aktivieren kann.

Alternativ könnte man via Adapter Stufe 3 aktivieren und dann mit einem Timerwert "n Sek" wieder auf die vorhergehende Stufe zurück. Das habe ich schon mit einem Script versucht. Dummerweise zeigt danach die CC ease immer "0x10 = Symbol MANUAL" an und nicht " 0x08 = Symbol AUTO ". und bleibt dann da MANUAL auf der Stufe welche ich nach dem Timer gesetzt habe Auto könnte man sicher danach wieder über den Adapter setzen. Aktuell habe ich auf dem Motherboard der Comfo an dem Input "Badezimmer Taster" BS<>GND einen Shelly1 dran der schliesst. Etwas kreativ aber funktioniert.

Ich bin leider nur der Bash mächtig.

**Comment by forelleblau** [comment]
Eine Boost-Funktion werde ich in den Adapter integrieren (nur über Adapter, Stufe 3 für n Minuten, ausser es erfolgt ein Stufenwechsel). Daneben werde ich versuchen, die Stosslüftungsfunktion doch noch auslösen zu können.
Für die Richtige Nutzung der Auto-Funktion fehlen in der Protokollbeschreibung wichtige Elemente. Für die Nutzung wäre dann ein Parallelbetrieb von CCEase und Adapter nötig, wovon ich aber dringend abrate. Die Autofunktion kann aber über ein Script im IoBroker ganz einfach nachgebaut werden (ist einfacher da zu erstellen als in der CC Ease).
Das manuelle Schalten des Bypasses muss ich definitiv beerdigen. Das ist mit dem Vorhandenen nur über eine Anpassung der Komforttemperatur zu machen.

**Comment by forelleblau** [comment]
v1.1.3 mit Boost ist verfügbar
