### ISSUE TITLE
readComfoairData - Fehler: ReferenceError: buffar is not defined

### ISSUE THREAD

**Issue by ivo443** [iobroker-community-adapters/ioBroker.comfoair#36]
Hallo zusammen

kriege seit dem Update auf 1.1.2 den Fehler "readComfoairData - Fehler: ReferenceError: buffar is not defined" im Log.
Der Adapter läuft aber.

Wäre froh um einen Input.

Grüsse
Ivo

Platform: linux
Architecture: x64
Node.js: v14.15.4
NPM: 6.14.10

**Comment by forelleblau** [comment]
Danke für den Hinweis. Hab den Fehler korrigiert. War tatsächlich ein Schreibfehler, fehlte an einer Stelle ein 'r' am Schluss.

Hab das korrigierte File auf Github hochgeladen. Bitte Adapter von da nochmals installieren, dann sollte der Fehler nicht mehr auftreten.

**Comment by ivo443** [comment]
> Danke für den Hinweis. Hab den Fehler korrigiert. War tatsächlich ein Schreibfehler, fehlte an einer Stelle ein 'r' am Schluss.
> 
> Hab das korrigierte File auf Github hochgeladen. Bitte Adapter von da nochmals installieren, dann sollte der Fehler nicht mehr auftreten.
